name: Update live

on:
  watch:
    types: [started]
  schedule:
    - cron: 0,30 * * * *

env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"

    - name: Update
      run: |
        # 央视源
        rm -f CCTV.m3u && wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CCTV.m3u
        sed -i -n '/央视/,+1p' CCTV.m3u
        sed -i '1i #EXTM3U' CCTV.m3u
        sed -i '/^\s*$/d' CCTV.m3u

        # 卫视源
        rm -f CNTV.m3u && touch CNTV.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV1.m3u && sed -i -n '/卫视/,+1p' CNTV1.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV2.m3u && sed -i -n '/数字/,+1p' CNTV2.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV3.m3u && sed -i -n '/百视/,+1p' CNTV3.m3u
        cat CNTV1.m3u >> CNTV.m3u
        cat CNTV2.m3u >> CNTV.m3u
        cat CNTV3.m3u >> CNTV.m3u
        rm -f CNTV1.m3u CNTV2.m3u CNTV3.m3u
        sed -i '1i #EXTM3U' CNTV.m3u
        sed -i '/^\s*$/d' CNTV.m3u

        # 酒店源
        rm -f live.m3u && touch live.m3u
        wget https://mirror.ghproxy.com/raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u -O live1.m3u && sed -i -n '/央视/,+1p' live1.m3u
        wget https://mirror.ghproxy.com/raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u -O live2.m3u && sed -i -n '/卫视/,+1p' live2.m3u
        wget https://mirror.ghproxy.com/raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u -O live3.m3u && sed -i -n '/地方/,+1p' live3.m3u
        wget https://mirror.ghproxy.com/raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u -O live4.m3u && sed -i -n '/数字/,+1p' live4.m3u
        wget https://mirror.ghproxy.com/raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u -O live5.m3u && sed -i -n '/国际/,+1p' live5.m3u
       
         cat live1.m3u >> live.m3u
         cat live2.m3u >> live.m3u
         cat live3.m3u >> live.m3u
         cat live4.m3u >> live.m3u
         cat live5.m3u >> live.m3u
        rm -f live1.m3u live2.m3u live3.m3u live4.m3u live5.m3u
        sed -i '/#EXTM3U/d' live.m3u
        sed -i '1i #EXTM3U x-tvg-url="https://mirror.ghproxy.com/raw.githubusercontent.com/qq49371114/tviptv/Files/EPG.xml" catchup="append" catchup-source="?playseek=${(b)yyyyMMddHHmmss}-${(e)yyyyMMddHHmmss}"' live.m3u
        sed -i '/^\s*$/d' live.m3u                                     
        

        # 整合源
        rm -f IPTVlive.m3u && touch IPTVlive.m3u
        cat CCTV.m3u >> IPTVlive.m3u
        cat CNTV.m3u >> IPTVlive.m3u
        cat live.m3u >> IPTVlive.m3u
        sed -i '/#EXTM3U/d' IPTVlive.m3u
        sed -i '1i #EXTM3U x-tvg-url="https://mirror.ghproxy.com/raw.githubusercontent.com/qq49371114/tviptv/Files/EPG.xml" catchup="append" catchup-source="?playseek=${(b)yyyyMMddHHmmss}-${(e)yyyyMMddHHmmss}"' IPTVlive.m3u
        sed -i '/^\s*$/d' IPTVlive.m3u

        # 节目源
        rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
        echo "Auto Update IPTVlive in ${{ steps.date.outputs.date }}" > README.md

    - name: Clean
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout --orphan latest_branch
        git add -A
        git commit -am "${{ steps.date.outputs.date }}"
        git branch -D Files
        git branch -m Files

    - name: Push
      run: git push -f origin Files


